slice_name: List of pregnant women receiving iron folate (ferus sulfate + folic acid)
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 3__table
  viz_type: table
  query_mode: raw
  groupby: []
  time_grain_sqla: P1D
  temporal_columns_lookup:
    birthdate: true
    date_started: true
  all_columns:
  - openmrs_id
  - patient_name
  - gender
  - age
  percent_metrics: []
  adhoc_filters:
  - expressionType: SIMPLE
    subject: date_started
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_d9fnlqb1o4w_4en0knzaid2
  order_by_cols:
  - '["date_started", false]'
  row_limit: 1000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  include_search: true
  show_cell_bars: false
  color_pn: true
  allow_rearrange_columns: true
  conditional_formatting: []
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":3,"type":"table"},"force":false,"queries":[{"filters":[{"col":"date_started","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["openmrs_id","patient_name","gender","age"],"orderby":[["date_started",false]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[]}],"form_data":{"datasource":"3__table","viz_type":"table","query_mode":"raw","groupby":[],"time_grain_sqla":"P1D","temporal_columns_lookup":{"birthdate":true,"date_started":true},"all_columns":["openmrs_id","patient_name","gender","age"],"percent_metrics":[],"adhoc_filters":[{"expressionType":"SIMPLE","subject":"date_started","operator":"TEMPORAL_RANGE","operatorId":"TEMPORAL_RANGE","comparator":"No
  filter","clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_d9fnlqb1o4w_4en0knzaid2"}],"order_by_cols":["[\"date_started\",
  false]"],"row_limit":1000,"server_page_length":10,"order_desc":true,"table_timestamp_format":"smart_date","include_search":true,"show_cell_bars":false,"color_pn":true,"allow_rearrange_columns":true,"conditional_formatting":[],"extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full","include_time":false},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: e395342b-578c-464e-82e9-680ce7c0b200
version: 1.0.0
dataset_uuid: 54e7e9a1-4295-4ead-9726-8aef532c85a5
