table_name: Patients receiving albendazole
main_dttm_col: birthdate
description: null
default_endpoint: null
offset: 0
cache_timeout: null
schema: public
sql: "SELECT \n  SUBSTRING(\n    identifiers \n    FROM \n      'Num\xE9ro Dossier:\
  \ ([^,]*)'\n  ) AS openmrs_id, \n  CONCAT_WS (\n    ' ', given_name, middle_name,\
  \ family_name\n  ) AS patient_name, \n  gender, \n  DATE_PART(\n    'year', \n \
  \   age(ord.date_created, birthdate)\n  ) AS age, \n  birthdate, \n  ord.date_created\
  \ AS date_created,\n  ct.name AS drug_name, \n  ct.uuid AS drug_uuid \nFROM \n \
  \ orders ord \n  LEFT JOIN concepts ct ON (\n    ord.concept_id = ct.concept_id\
  \ \n    AND ct.concept_id IS NOT NULL\n  ) \n  LEFT JOIN patients pt ON (\n    ord.patient_id\
  \ = pt.patient_id \n    AND pt.patient_id IS NOT NULL\n  ) \nWHERE \n  ord.voided\
  \ IS FALSE -- Drug orders only\n  AND ord.order_type_uuid = '16bb6bcf-2e81-4ba5-8583-ff4913201a72'\
  \ -- Albendazole\n  AND ct.uuid IN (\n    '8f668b49-584f-4cba-b0f2-817a8aaf50c4'\n\
  \  )\n  \nORDER BY ord.date_created;"
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
normalize_columns: false
always_filter_main_dttm: false
uuid: 112cd19a-9a3a-45a5-95cb-e1f1b198eece
metrics:
- metric_name: count
  verbose_name: Total Entries
  metric_type: count
  expression: COUNT(*)
  description: Total number of records in the dataset, including all rows regardless
    of values
  d3format: null
  currency: null
  extra:
    warning_markdown: ''
  warning_text: null
columns:
- column_name: age
  verbose_name: Age (years)
  is_dttm: false
  is_active: true
  type: FLOAT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: openmrs_id
  verbose_name: Patient ID
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: gender
  verbose_name: Gender
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: patient_name
  verbose_name: Name
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: date_created
  verbose_name: null
  is_dttm: true
  is_active: true
  type: DATETIME
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: birthdate
  verbose_name: null
  is_dttm: true
  is_active: true
  type: DATE
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: drug_name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: drug_uuid
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
version: 1.0.0
database_uuid: 4e5f4045-a62d-4964-b719-58229a60e7fe
