services:
  odoo:
    environment:
      - ADDONS=sale_management,stock,account_account,purchase,mrp,mrp_product_expiry,product_expiry,l10n_generic_coa,odoo_initializer,ozone_settings,server_environment,stock_extension,auth_oidc_environment,auth_oidc
