services:
  odoo:
    environment:
      - ADDONS=sale_management,stock,account_account,purchase,mrp,odoo_initializer,ozone_settings,mrp_product_expiry,product_expiry,l10n_generic_coa,stock_extension

  env-substitution:
    environment:
      - ODOO_HOST=http://odoo
      - ODOO_USER=${ODOO_USER}
      - ODOO_PASSWORD=${ODOO_PASSWORD}
      - ODOO_DB=${ODOO_DATABASE}

  eip-odoo-openmrs:
    environment:
      - EIP_FHIR_RESOURCES=Patient,ServiceRequest,MedicationRequest,SupplyRequest,Procedure
      - EIP_DRUG_ORDER_TYPE_UUID=16bb6bcf-2e81-4ba5-8583-ff4913201a72
